/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-08-29 15:43:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sale;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fcontacts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.\r\n");
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/jQuery_WeUI/lib/weui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/jQuery_WeUI/css/jquery-weui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/assets/css/demos.css\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body ontouchstart>\r\n");
      out.write("\t\r\n");

    //接收URL传递来的参数
    String company = request.getParameter("company");

      out.write("\r\n");
      out.write("    <header class='demos-header'>\r\n");
      out.write("      <h1 class=\"demos-title\">添加联系人</h1>\r\n");
      out.write("    </header>\r\n");
      out.write("    <form id=\"form1\">\r\n");
      out.write("  \r\n");
      out.write("      <div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t     <div class=\"weui-cell\">\r\n");
      out.write("\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">联系人</label></div>\r\n");
      out.write("\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t         <input class=\"weui-input\" id=\"contacts_name\" name=\"contacts_name\" type=\"text\" placeholder=\"请输入真实姓名\" value=\"\" required=\"required\" >\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t     </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"weui-cells weui-cells_form\" >\r\n");
      out.write("\t     <div class=\"weui-cell\">\r\n");
      out.write("\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">公司名称</label></div>\r\n");
      out.write("\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t         <input class=\"weui-input\" id=\"company_name\" name=\"company_name\" type=\"text\" readonly=\"readonly\" value=\"");
      out.print(company);
      out.write("\" required=\"required\" >\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t     </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t     <div class=\"weui-cell\">\r\n");
      out.write("\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">联系部门</label></div>\r\n");
      out.write("\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t         <input class=\"weui-input\" id=\"department\" name=\"department\" type=\"text\" placeholder=\"请输入所属部门\" value=\"\" required=\"required\" >\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t     </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t     <div class=\"weui-cell\">\r\n");
      out.write("\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">职务</label></div>\r\n");
      out.write("\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t         <input class=\"weui-input\" id=\"post\" name=\"post\" type=\"text\" placeholder=\"请输入担任职务\" value=\"\" required=\"required\" >\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t     </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t     <div class=\"weui-cell\">\r\n");
      out.write("\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">手机号</label></div>\r\n");
      out.write("\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t         <input class=\"weui-input\" id=\"tel\" name=\"tel\" type=\"tel\" placeholder=\"请输入手机号\" required=\"required\" >\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t     </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"weui-btn-area\">\r\n");
      out.write("      <a class=\"weui-btn weui-btn_primary\" href=\"javascript:\" id=\"showTooltips\" >添加</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/jQuery_WeUI/lib/jquery-2.1.4.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/jQuery_WeUI/lib/fastclick.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  $(function() {\r\n");
      out.write("    FastClick.attach(document.body);\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/jQuery_WeUI/js/jquery-weui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("  \t  //验证是否有字段为空\r\n");
      out.write("\t  function validateForm() {\r\n");
      out.write("\t\t  \tvar contacts_name=$('#contacts_name').val();\r\n");
      out.write("\t    \tvar department=$('#department').val();\r\n");
      out.write("\t    \tvar post=$('#post').val();\r\n");
      out.write("\t        var tel = $('#tel').val();\r\n");
      out.write("\t        if(contacts_name==\"\"||department==\"\"||post==\"\"){\r\n");
      out.write("\t        \t/* alert(time==\"\"); */\r\n");
      out.write("\t        \t$.toptip('任何字段都不能为空！');\r\n");
      out.write("\t        \treturn  false;\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(!tel || !/1[3|4|5|7|8]\\d{9}/.test(tel)){\r\n");
      out.write("\t        \t$.toptip('请输入正确的手机号');\r\n");
      out.write("\t        \treturn  false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t      // 在键盘按下并释放及提交后验证提交表单\r\n");
      out.write("\t      return true;\r\n");
      out.write("\t\t}\r\n");
      out.write("      $(\"#showTooltips\").click(function() {\r\n");
      out.write("    \t/* var contacts_name=$('#contacts_name').val();\r\n");
      out.write("    \tvar department=$('#department').val();\r\n");
      out.write("    \tvar post=$('#post').val();\r\n");
      out.write("        var tel = $('#tel').val(); */\r\n");
      out.write("        if(!validateForm()){\r\n");
      out.write("        \treturn \"\";\r\n");
      out.write("        }else{\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("      \t\t     url: '");
      out.print(request.getContextPath());
      out.write("/contacts.do',\r\n");
      out.write("      \t\t     data:$(\"#form1\").serialize(), \r\n");
      out.write("      \t\t     type: \"post\",\r\n");
      out.write("      \t\t     dataType : \"json\",\r\n");
      out.write("      \t\t  })\r\n");
      out.write("      \t\t  .done(function( data ) {\r\n");
      out.write("      \t\t\t //alert(data);\r\n");
      out.write("      \t\t     if(data==true){\r\n");
      out.write("      \t\t    \t\r\n");
      out.write("      \t\t    \twindow.history.go(-1);\r\n");
      out.write("      \t\t    \t \r\n");
      out.write("      \t\t     }else  if(data==false){\r\n");
      out.write("      \t\t    \t //alert(\"已经注册！请勿重复\");\r\n");
      out.write("      \t\t    \twindow.location.href=\"");
      out.print(request.getContextPath() );
      out.write("/common/error.jsp\";\r\n");
      out.write("      \t\t    \t//window.location.href=\"OAuth/error.jsp\";\r\n");
      out.write("      \t\t     }\r\n");
      out.write("      \t\t  })\r\n");
      out.write("      \t\t  .fail(function( xhr, status, errorThrown ) {\r\n");
      out.write("      \t\t    //alert( \"Sorry, there was a problem!\" );\r\n");
      out.write("      \t\t    console.log( \"Error: \" + errorThrown );\r\n");
      out.write("      \t\t    console.log( \"Status: \" + status );\r\n");
      out.write("      \t\t    console.dir( xhr );\r\n");
      out.write("      \t\t  })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* alert(\"+++\");\r\n");
      out.write("         window.history.back(-1); */\r\n");
      out.write("      });\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
