/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-08-29 15:43:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sale;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class my_005fdaily_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- <title>我的日报</title> -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.\r\n");
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../jQuery_WeUI/lib/weui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../jQuery_WeUI/css/jquery-weui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/demos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/jquery-ui.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"../assets/jquery.autocomplete.css\"> -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body ontouchstart>\r\n");

String time = request.getParameter("time");
String company=request.getParameter("company");
String contacts=request.getParameter("contacts");
String stage=request.getParameter("stage");
String budget = request.getParameter("budget");
String intention=request.getParameter("intention");
String discount=request.getParameter("discount");
String progress=request.getParameter("progress");
String point=request.getParameter("point");
String advice=request.getParameter("advice");
if(time==null||contacts==null||company==null||advice==null||stage==null||budget==null||intention==null||discount==null||progress==null||point==null){
	/* alert(time==""); */
	time="";
	company="";
	stage="";
	budget="";
	intention="";
	discount="";
	progress="";
	point="";
	advice="";
	contacts="";
}

      out.write("\r\n");
      out.write("\t\t<header class='demos-header'>\r\n");
      out.write("\t\t\t<h1 class=\"demos-title\">我的日报</h1>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<from id=\"form2\">\r\n");
      out.write("\t\t\t<div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t\t\t<div class=\"weui-cell\">\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__hd\">\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class=\"weui-label\">时间</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__bd\">\r\n");
      out.write("\t\t\t\t\t<input class=\"weui-input\" name=\"time\" id=\"time\" type=\"datetime-local\" value=\"");
      out.print(time);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t        <div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t\t     <div class=\"weui-cell\">\r\n");
      out.write("\t\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">客户公司</label></div>\r\n");
      out.write("\t\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t\t         <input class=\"weui-input\" name=\"company\" id=\"company\" type=\"text\" placeholder=\"请输入客户公司\"value=\"");
      out.print(company);
      out.write("\" required=\"required\" >\r\n");
      out.write("\t\t       </div>\r\n");
      out.write("\t\t       <div class=\"weui-cell__ft\">\r\n");
      out.write("\t\t          <button class=\"weui-vcode-btn\" onClick=\"queryContacts()\">获取联系人</button>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t\t<div class=\"weui-cells weui-cells_form\"\t>\r\n");
      out.write("\t\t\t     <div class=\"weui-cell\" >\r\n");
      out.write("\t\t\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">联系人</label></div>\r\n");
      out.write("\t\t\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t\t\t         <input class=\"weui-input\" name=\"contacts\" id=\"contacts\" type=\"text\" value=\"");
      out.print(contacts);
      out.write("\">\r\n");
      out.write("\t\t\t       </div>\r\n");
      out.write("\t\t\t       <img src=\"../assets/images/add.png\" onClick=\"addContacts()\">\r\n");
      out.write("\t\t\t       \t\r\n");
      out.write("\t\t\t     </div> \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- \r\n");
      out.write("\t\t\t<div class=\"button_sp_area\" align=\"center\">\r\n");
      out.write("\t\t       <a href=\"javascript:;\" class=\"weui-btn weui-btn_mini weui-btn_primary\">新增联系人</a>\r\n");
      out.write("\t\t       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t       <a href=\"javascript:;\" class=\"weui-btn weui-btn_mini weui-btn_default\">刷新联系人</a>\r\n");
      out.write("\t\t    </div> -->\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <div class=\"weui-cells weui-cell_select\">\r\n");
      out.write("\t\t\t     <div class=\"weui-cell\">\r\n");
      out.write("\t\t\t       <div class=\"weui-cell__hd\"><label for=\"name\" class=\"weui-label\">进展阶段</label></div>\r\n");
      out.write("\t\t\t       <div class=\"weui-cell__bd\">\r\n");
      out.write("\t\t\t         <select class=\"weui-select\" name=\"stage\" id=\"stage\" value=\"");
      out.print(stage);
      out.write("\"required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"接触阶段\">接触阶段</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"方案阶段\">方案阶段</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"待签合同阶段\">待签合同阶段</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"回款阶段\">回款阶段</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t       </div>\r\n");
      out.write("\t\t\t     </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"weui-cell weui-cells_form\">\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__hd\">\r\n");
      out.write("\t\t\t\t\t<label class=\"weui-label\">项目预算</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__bd\">\r\n");
      out.write("\t\t\t\t\t<input class=\"weui-input\" name=\"budget\" id=\"budget\" type=\"text\" value=\"");
      out.print(budget );
      out.write("\" required=\"required\" placeholder=\"若无项目预算直接填写无\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"weui-cell weui-cells_form\">\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__hd\">\r\n");
      out.write("\t\t\t\t\t<label class=\"weui-label\">意向屏点</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__bd\">\r\n");
      out.write("\t\t\t\t\t<input class=\"weui-input\" name=\"intention\" id=\"intention\" type=\"text\" value=\"");
      out.print(intention );
      out.write("\"required=\"required\" placeholder=\"请输入意向屏点\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"weui-cell weui-cells_form\">\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__hd\">\r\n");
      out.write("\t\t\t\t\t<label class=\"weui-label\">折扣</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"weui-cell__bd\">\r\n");
      out.write("\t\t\t\t\t<input class=\"weui-input\" name=\"discount\" id=\"discount\" type=\"text\" value=\"");
      out.print(discount );
      out.write("\" required=\"required\" placeholder=\"请输入折扣\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"weui-cells__title\"><font size=\"4\" color=\"black\">进展</font></div>\r\n");
      out.write("\t    <div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t      <div class=\"weui-cell\">\r\n");
      out.write("\t        <div class=\"weui-cell__bd\">\r\n");
      out.write("\t          <textarea class=\"weui-textarea\" name=\"progress\" id=\"progress\" placeholder=\"请输入文本\"  rows=\"3\" required=\"required\">");
      out.print(progress );
      out.write("</textarea>\r\n");
      out.write("\t          <div class=\"weui-textarea-counter\"><span class=\"count\">0</span>/500</div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"weui-cells__title\"><font size=\"4\" color=\"black\">关键点、难点、及所需支持</font></div>\r\n");
      out.write("\t    <div class=\"weui-cells weui-cells_form\">\r\n");
      out.write("\t      <div class=\"weui-cell\">\r\n");
      out.write("\t        <div class=\"weui-cell__bd\">\r\n");
      out.write("\t          <textarea class=\"weui-textarea\" name=\"point\" id=\"point\" placeholder=\"请输入文本\" rows=\"3\"  required=\"required\">");
      out.print(point );
      out.write("</textarea>\r\n");
      out.write("\t          <div class=\"weui-textarea-counter\"><span class=\"count\">0</span>/500</div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <div class=\"weui-cells weui-cells_form\" style=\"display:none\">\r\n");
      out.write("\t      <div class=\"weui-cell\">\r\n");
      out.write("\t        <div class=\"weui-cell__bd\">\r\n");
      out.write("\t          <textarea class=\"weui-textarea\" name=\"advice\" id=\"advice\" >");
      out.print(advice );
      out.write("</textarea>\r\n");
      out.write("\t          \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"weui-btn-area\">\r\n");
      out.write("\t\t\t\t<a class=\"weui-btn weui-btn_primary\" href=\"javascript:\"\r\n");
      out.write("\t\t\t\t\tid=\"showTooltips\">确定</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</from>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!-- </div> -->\r\n");
      out.write("\t<script src=\"../jQuery_WeUI/lib/jquery-2.1.4.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/assets/jquery-ui.js\"></script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/assets/jquery.cookie.js\"></script>\r\n");
      out.write("\t<script src=\"../jQuery_WeUI/lib/fastclick.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t  $(function() {\r\n");
      out.write("\t    FastClick.attach(document.body);\r\n");
      out.write("\t    \r\n");
      out.write("\t    //$('#contacts').prop('selectedIndex', 0);\r\n");
      out.write("\t    var max = 500;\r\n");
      out.write("\t    $('.weui-textarea').on('input', function(){\r\n");
      out.write("\t       var text = $(this).val();\r\n");
      out.write("\t       var len = text.length;\r\n");
      out.write("\t       $('.count').text(len);\r\n");
      out.write("\t       if(len > max){\r\n");
      out.write("\t         $(this).closest('.weui_cell').addClass('weui_cell_warn');\r\n");
      out.write("\t       }\r\n");
      out.write("\t       else{\r\n");
      out.write("\t         $(this).closest('.weui_cell').removeClass('weui_cell_warn');\r\n");
      out.write("\t       }\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t   ");
      out.write("\r\n");
      out.write("\t  });\r\n");
      out.write("\r\n");
      out.write("\t  //验证是否有字段为空\r\n");
      out.write("\t  function validateForm() {\r\n");
      out.write("\t\t  \tvar flag=true;\r\n");
      out.write("\t\t    var time=$('#time').val();\r\n");
      out.write("\t\t  \tvar company=$('#company').val();\r\n");
      out.write("\t\t  \tvar contacts=$('#contacts').val();\r\n");
      out.write("\t\t  \t//var select\r\n");
      out.write("\t        var stage = $('#stage').val();\r\n");
      out.write("\t        var budget=$('#budget').val();\r\n");
      out.write("\t        var intention=$('#intention').val();\r\n");
      out.write("\t        var discount=$('#discount').val();\r\n");
      out.write("\t        var progress=$('#progress').val();\r\n");
      out.write("\t        var point=$('#point').val();\r\n");
      out.write("\t        if(time==\"\"||company==\"\"||contacts==\"\"||stage==\"\"||budget==\"\"||intention==\"\"||discount==\"\"||progress==\"\"||point==\"\"){\r\n");
      out.write("\t        \t/* alert(time==\"\"); */\r\n");
      out.write("\t        \t$.toptip('任何字段都不能为空！');\r\n");
      out.write("\t        \tflag= false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t      // 在键盘按下并释放及提交后验证提交表单\r\n");
      out.write("\t      return flag;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t   \r\n");
      out.write("\t  //验证cookie是否过期\r\n");
      out.write("\t  function validateCookie(){\r\n");
      out.write("\t\t var cookie=$.cookie('openid');\r\n");
      out.write("\t\t if(cookie==null){\r\n");
      out.write("\t\t    \twindow.location.href=\"");
      out.print(request.getContextPath() );
      out.write("/OAuth/oauth_index.jsp\";\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  //存储当前变量\r\n");
      out.write("\t  function storage_parameter(){\r\n");
      out.write("\t\t    var time=$('#time').val();\r\n");
      out.write("\t\t  \tvar company=$('#company').val();\r\n");
      out.write("\t\t  \tvar contacts=$('#contacts').val();\r\n");
      out.write("\t\t  \t//var select\r\n");
      out.write("\t        var stage = $('#stage').val();\r\n");
      out.write("\t        var budget=$('#budget').val();\r\n");
      out.write("\t        var intention=$('#intention').val();\r\n");
      out.write("\t        var discount=$('#discount').val();\r\n");
      out.write("\t        var progress=$('#progress').val();\r\n");
      out.write("\t        var point=$('#point').val();\r\n");
      out.write("\t        var advice=$('#advice').val();\r\n");
      out.write("\t       \r\n");
      out.write("\t        var url=\"http://daily.s1.natapp.cc/Daily/sale/my_daily.jsp?time=\"+time+\r\n");
      out.write("\t        \t\t\"&company=\"+company+\"&stage=\"+stage+\"&contacts=\"+contacts+\"&budget=\"+budget+\"&intention=\"+intention+\r\n");
      out.write("\t        \t\t\"&discount=\"+discount+\"&progress=\"+progress+\"&point=\"+point+\"&advice=\"+advice;\r\n");
      out.write("\t        return url;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  //根据公司查询联系人\r\n");
      out.write("\t  function queryContacts(){\r\n");
      out.write("\t\t  //location.reload(true)  ;\r\n");
      out.write("\t\t /*  var url=storage_parameter();\r\n");
      out.write("\t\t  alert(url);\r\n");
      out.write("\t\t  window.location.href=url; */\r\n");
      out.write("\t\t  //window.location.reload();\r\n");
      out.write("\t\t  //initContacts(\"\");\r\n");
      out.write("\t\t  var company_name=$('#company').val();\r\n");
      out.write("\t\t  if(company_name==\"\")\r\n");
      out.write("\t\t  { \r\n");
      out.write("\t\t\t  $.toptip('客户公司不能为空！');\r\n");
      out.write("\t\t\t  return \"\";\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t  $.ajax({\r\n");
      out.write("    \t\t     url: '");
      out.print(request.getContextPath());
      out.write("/writeDaily.do',\r\n");
      out.write("    \t\t     data:{\"company_name\":company_name}, \r\n");
      out.write("    \t\t     type: \"get\",\r\n");
      out.write("    \t\t     dataType : \"text\",\r\n");
      out.write("    \t\t  })\r\n");
      out.write("    \t\t  .done(function( data ) {\r\n");
      out.write("    \t\t\t // alert(data);\r\n");
      out.write("    \t\t\t document.getElementById('contacts').value=data;\r\n");
      out.write("    \t\t\t var items=data.split(\",\");\r\n");
      out.write("    \t\t\t if(items==\"\"){\r\n");
      out.write("    \t\t\t\t $.toast(\"查询客户公司无相关联系人\", \"text\");\r\n");
      out.write("    \t\t\t }else {\r\n");
      out.write("    \t\t\t\t initContacts(items); \r\n");
      out.write("    \t\t\t }\r\n");
      out.write("    \t\t  })\r\n");
      out.write("    \t\t  .fail(function( xhr, status, errorThrown ) {\r\n");
      out.write("    \t\t    //alert( \"Sorry, there was a problem!\" );\r\n");
      out.write("    \t\t    console.log( \"Error: \" + errorThrown );\r\n");
      out.write("    \t\t    console.log( \"Status: \" + status );\r\n");
      out.write("    \t\t    console.dir( xhr );\r\n");
      out.write("    \t\t  })\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  //根据客户公司初始化联系人\r\n");
      out.write("\t  function initContacts(items){\r\n");
      out.write("\t\t  //alert(items);\r\n");
      out.write("\t\t  $(\"#contacts\").select({\r\n");
      out.write("\t\t    title: \"选择联系人\",\r\n");
      out.write("\t\t    items: items,\r\n");
      out.write("\t\t    multi: true,\r\n");
      out.write("\t\t    min: 0,\r\n");
      out.write("\t\t    max: 10,\r\n");
      out.write("\t\t    onChange: function(d) {\r\n");
      out.write("\t\t      console.log(this, d);\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    onClose: function() {\r\n");
      out.write("\t\t    \t//解决select赋值只能渲染一次的问题\r\n");
      out.write("\t\t    \tvar url=storage_parameter();\r\n");
      out.write("\t\t\t\t//alert(url);\r\n");
      out.write("\t\t\t\twindow.location.href=url; \r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    onOpen: function() {\r\n");
      out.write("\t\t      console.log(\"open\");\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function addContacts(){\r\n");
      out.write("\t\t  var company=$('#company').val();\r\n");
      out.write("\t\t  if(company==\"\"){$.toptip('请输入客户公司');return \"\";}\r\n");
      out.write("\t\t  window.location.href = \"");
      out.print(request.getContextPath() );
      out.write("/sale/add_contacts.jsp?company=\"+company;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  $(\"#showTooltips\").click(function() {\r\n");
      out.write("\t\t if(validateForm()==false){\r\n");
      out.write("\t\t\t  return \"\";\r\n");
      out.write("\t\t  } \r\n");
      out.write("\t\t  //cookie验证(验证openid是否存在)\r\n");
      out.write("\t\t   validateCookie();\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    var time=$('#time').val();\r\n");
      out.write("\t\t  \tvar company=$('#company').val();\r\n");
      out.write("\t\t  \tvar contacts=$('#contacts').val();\r\n");
      out.write("\t\t  \t//var select\r\n");
      out.write("\t        var stage = $('#stage').val();\r\n");
      out.write("\t        var budget=$('#budget').val();\r\n");
      out.write("\t        var intention=$('#intention').val();\r\n");
      out.write("\t        var discount=$('#discount').val();\r\n");
      out.write("\t        var progress=$('#progress').val();\r\n");
      out.write("\t        var point=$('#point').val();\r\n");
      out.write("\t        var advice=$('#advice').val();\r\n");
      out.write("\t        /* var sex=$('#sex input[name=\"radio1\"]:checked').val(); */\r\n");
      out.write("        \t $.ajax({\r\n");
      out.write("       \t\t     url: '");
      out.print(request.getContextPath());
      out.write("/writeDaily.do',\r\n");
      out.write("       \t\t     data:{\"time\":time,\"company\":company,\"contacts\":contacts,\"stage\":stage,\r\n");
      out.write("       \t\t    \t     \"budget\":budget,\"intention\":intention,\"discount\":discount,\"progress\":progress,\"point\":point,\"advice\":advice}, \r\n");
      out.write("       \t\t     type: \"post\",\r\n");
      out.write("       \t\t     dataType : \"json\",\r\n");
      out.write("       \t\t  })\r\n");
      out.write("       \t\t  .done(function( data ) {\r\n");
      out.write("       \t\t\t //alert(data);\r\n");
      out.write("       \t\t     if(data==true){\r\n");
      out.write("       \t\t    \t\r\n");
      out.write("       \t\t    \t$.toast(\"提交成功\");\r\n");
      out.write("       \t\t    \tWeixinJSBridge.call('closeWindow');\r\n");
      out.write("       \t\t     }else  if(data==false){\r\n");
      out.write("       \t\t    \t //alert(\"已经注册！请勿重复\");\r\n");
      out.write("       \t\t    \t $.toast(\"提交失败\", \"cancel\");\r\n");
      out.write("       \t\t    \t//window.location.href=\"");
      out.print(request.getContextPath() );
      out.write("/common/error.jsp\";\r\n");
      out.write("       \t\t    \t//window.location.href=\"OAuth/error.jsp\";\r\n");
      out.write("       \t\t     }\r\n");
      out.write("       \t\t  })\r\n");
      out.write("       \t\t  .fail(function( xhr, status, errorThrown ) {\r\n");
      out.write("       \t\t    //alert( \"Sorry, there was a problem!\" );\r\n");
      out.write("       \t\t    console.log( \"Error: \" + errorThrown );\r\n");
      out.write("       \t\t    console.log( \"Status: \" + status );\r\n");
      out.write("       \t\t    console.dir( xhr );\r\n");
      out.write("       \t\t  })\r\n");
      out.write("\t        \r\n");
      out.write("\t      }); \r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"../jQuery_WeUI/js/jquery-weui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t/*刷新\r\n");
      out.write("\t$('.weui-tab__bd-item').pullToRefresh().on('pull-to-refresh', function (done) {\r\n");
      out.write("\t    var self = this\r\n");
      out.write("\t    setTimeout(function() {\r\n");
      out.write("\t      $(self).pullToRefreshDone();\r\n");
      out.write("\t    }, 2000)\r\n");
      out.write("\t  }) */\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
